set -g mouse on
bind | split-window -h
bind - split-window -v

# 默认的插件列表
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible' # 包含一些通用的基础好用配置

# --- 以后你想加的新插件，直接写在这两条之间 ---
# 比如：set -g @plugin 'github用户名/插件仓库名'
set -g @plugin 'tmux-plugins/tmux-yank'
# ----------------------------------------

set -g @yank_selection_mouse 'clipboard'

# 初始化 TMUX 插件管理器 (这行必须放在文件最底部)
run '~/.tmux/plugins/tpm/tpm'
